version: '3.4'

services:
  archaeologistuptimemonitor:
    image: archaeologist-uptime-monitor
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
